[tools]
ansible = { version = "14.2.0", pipx_args = "--include-deps", uvx = false }
erlang = "29.0.4"
go = "1.26.5"
java = "26.0.2"
node = "26.5.1"
php = "8.5.9"
pipx = "1.16.3"
pnpm = "11.18.0"
rebar = { version = "3.27.0", asset_pattern = "rebar3" }
ruby = "4.0.6"
terraform = "1.15.8"
usage = "4.0.0"
zig = "0.16.0"
